import CoreGraphics
import Foundation
import ImageIO
import IslandStore

/// Animation of a Sprite — the pixel-art bot that stands for one Session in
/// the compact Island (issue #11). Its animation encodes the Session state at
/// a glance, with the #8 state tints carried by the sprite itself (green
/// check, orange question mark).
public enum SpriteAnimation: String, CaseIterable, Sendable {
    case working
    case sleeping
    case finished
    case question
    /// Drawn in the sheet but reserved: no Session state produces it yet.
    case error

    /// The one animation a Session state shows in the compact bar.
    public static func animation(for state: SessionState) -> SpriteAnimation {
        switch state {
        case .running: .working
        case .idle: .sleeping
        case .ended: .finished
        case .waiting: .question
        }
    }
}

/// Layout and pace of one embedded sprite sheet: one row per animation, one
/// 16×16 frame per column. Pure description — the SwiftUI layer crops the
/// PNG, the timing below is what the tests pin down.
public struct SpriteSheet: Sendable {
    /// Per-animation loop: number of frames and pace, gentle by design
    /// (validated on the planches: 1.5–7 fps depending on the state).
    struct Loop {
        let frames: Int
        let fps: Double
    }

    let loops: [SpriteAnimation: Loop]

    /// The bot sheet validated on planche C.
    public static let bot = SpriteSheet(loops: [
        .working: Loop(frames: 4, fps: 4),
        .sleeping: Loop(frames: 2, fps: 1.5),
        .finished: Loop(frames: 4, fps: 3),
        .question: Loop(frames: 3, fps: 2.5),
        .error: Loop(frames: 6, fps: 7),
    ])

    /// The Extended-card glyph sheet: the bot screen's glyphs alone, 2×,
    /// one gentle loop per state (check draws itself, question blinks like
    /// on the robot, error cross shakes, typing dots, floating z).
    public static let glyphs = SpriteSheet(loops: [
        .working: Loop(frames: 4, fps: 4),
        .sleeping: Loop(frames: 2, fps: 1.5),
        .finished: Loop(frames: 4, fps: 3),
        .question: Loop(frames: 3, fps: 2.5),
        .error: Loop(frames: 2, fps: 7),
    ])

    /// The isle logo sheet: a single gentle loop (palms swaying), stored on
    /// the `.working` row — the isle has no Session state to encode.
    public static let isle = SpriteSheet(loops: [
        .working: Loop(frames: 2, fps: 1.5)
    ])

    /// Widest loop of the sheet — the PNG's column count.
    public var maxFrames: Int {
        loops.values.map(\.frames).max() ?? 1
    }

    /// The embedded sheet PNG (generated by scripts/generate_sprites.py).
    public func image(named name: String) -> CGImage? {
        guard let url = Self.resourceURL(name: name, ext: "png"),
              let source = CGImageSourceCreateWithURL(url as CFURL, nil)
        else { return nil }
        return CGImageSourceCreateImageAtIndex(source, 0, nil)
    }

    /// Locates an embedded resource across the layouts island runs in.
    ///
    /// In the packaged `.app`, the SwiftPM resource bundle lives under
    /// `Contents/Resources/` — the only codesign-legal spot. The generated
    /// `Bundle.module` accessor instead looks for it at the `.app` *root*,
    /// where codesign forbids content ("unsealed contents in the bundle root"),
    /// so a packaged build must resolve the bundle itself. We try the main
    /// bundle's Resources first and only fall back to `Bundle.module` (dev and
    /// tests) afterwards — never touching it in the packaged path, since its
    /// accessor `fatalError`s when the bundle is absent.
    static func resourceURL(name: String, ext: String) -> URL? {
        if let resources = Bundle.main.resourceURL {
            let nested = resources.appendingPathComponent("Island_IslandUI.bundle")
            if let bundle = Bundle(url: nested),
               let url = bundle.url(forResource: name, withExtension: ext) {
                return url
            }
        }
        if let url = Bundle.main.url(forResource: name, withExtension: ext) {
            return url
        }
        return Bundle.module.url(forResource: name, withExtension: ext)
    }

    /// Which frame the looping animation shows after `elapsed` seconds.
    public func frameIndex(for animation: SpriteAnimation, elapsed: TimeInterval) -> Int {
        guard let loop = loops[animation], elapsed > 0 else { return 0 }
        return Int(elapsed * loop.fps) % loop.frames
    }

    /// Pixel size of one frame, and of the square grid the sheet is cut on.
    public static let frameSize = 16

    /// Where a frame lives in the sheet PNG: one row per animation (in
    /// declaration order), one column per frame.
    public func frameRect(for animation: SpriteAnimation, frame: Int) -> CGRect {
        let size = Self.frameSize
        let row = SpriteAnimation.allCases.firstIndex(of: animation) ?? 0
        return CGRect(x: frame * size, y: row * size, width: size, height: size)
    }
}
