#!/usr/bin/env python3
"""Exports the bot Sprites to the Totem firmware as an indexed C++ header
(issue #159).

Reads the shipped sheet Sources/IslandUI/Resources/Sprites/bot.png as is
(never regenerates the app PNGs: that is scripts/generate_sprites.py's job)
and the per-animation frames/fps from Sources/IslandUI/Sprites.swift, the
only place the fps exist. Writes firmware/src/generated/totem_sprites.h:
an indexed palette (index 0 = transparent), one 16x16 byte grid per frame
and the frames/fps table of the working, sleeping, finished and question
rows. The error row is not exported (no aggregated state shows it).

    python3 scripts/export_totem_sprites.py          # (re)write the header
    python3 scripts/export_totem_sprites.py --check  # exit 1 if out of date

Deterministic: the same inputs always give the same bytes.
"""

import os
import re
import sys
from decimal import Decimal

from PIL import Image

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SHEET = os.path.join(ROOT, "Sources", "IslandUI", "Resources", "Sprites", "bot.png")
SWIFT = os.path.join(ROOT, "Sources", "IslandUI", "Sprites.swift")
OUTPUT = os.path.join(ROOT, "firmware", "src", "generated", "totem_sprites.h")

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from generate_sprites import BOT_LOOPS, SIZE  # noqa: E402  (no side effect: main is guarded)

# Exported rows, in sheet order. `error` (last row) stays out.
EXPORTED = ["working", "sleeping", "finished", "question"]


def fail(message):
    sys.exit(f"export_totem_sprites: {message}")


def swift_bot_loops():
    """{animation: (frames, fps as Decimal)} from `SpriteSheet.bot`."""
    with open(SWIFT, encoding="utf-8") as source:
        text = source.read()
    block = re.search(r"static let bot = SpriteSheet\(loops: \[(.*?)\]\)", text, re.S)
    if block is None:
        fail(f"SpriteSheet.bot not found in {SWIFT}")
    loops = {
        name: (int(frames), Decimal(fps))
        for name, frames, fps in re.findall(
            r"\.(\w+): Loop\(frames: (\d+), fps: ([0-9.]+)\)", block.group(1)
        )
    }
    return loops


def rows():
    """[(name, row index, frames, fps milli)] for the exported animations."""
    order = [name for name, _ in BOT_LOOPS]
    swift = swift_bot_loops()
    out = []
    for name in EXPORTED:
        if name not in swift:
            fail(f"'{name}' missing from SpriteSheet.bot")
        frames, fps = swift[name]
        if dict(BOT_LOOPS)[name] != frames:
            fail(f"'{name}': Sprites.swift says {frames} frames, generate_sprites.py says {dict(BOT_LOOPS)[name]}")
        milli = fps * 1000
        if milli != milli.to_integral_value():
            fail(f"'{name}': fps {fps} is not a whole number of millihertz")
        out.append((name, order.index(name), frames, int(milli)))
    return out


def read_frames(image, row, frames):
    """Each frame as 256 RGBA tuples, row-major."""
    columns = image.width // SIZE
    grids = []
    for column in range(columns):
        grid = [
            image.getpixel((column * SIZE + x, row * SIZE + y))
            for y in range(SIZE)
            for x in range(SIZE)
        ]
        opaque = any(pixel[3] for pixel in grid)
        if column < frames and not opaque:
            fail(f"row {row} frame {column} is empty")
        if column >= frames and opaque:
            fail(f"row {row} has pixels past its {frames} frames")
        if column < frames:
            grids.append(grid)
    return grids


def build():
    image = Image.open(SHEET).convert("RGBA")
    if image.width % SIZE or image.height != SIZE * len(BOT_LOOPS):
        fail(f"unexpected sheet size {image.size}")

    palette = [None]  # index 0: transparent
    table = []
    frames_out = []
    for name, row, frames, fps_milli in rows():
        first = len(frames_out)
        for grid in read_frames(image, row, frames):
            indices = []
            for r, g, b, a in grid:
                if a == 0:
                    indices.append(0)
                    continue
                if a != 255:
                    fail(f"row {row}: semi-transparent pixel (alpha {a})")
                rgb = (r << 16) | (g << 8) | b
                if rgb not in palette:
                    palette.append(rgb)
                indices.append(palette.index(rgb))
            frames_out.append((name, len(frames_out) - first, indices))
        table.append((name, first, frames, fps_milli))

    lines = [
        "// generated by scripts/export_totem_sprites.py from",
        "// Sources/IslandUI/Resources/Sprites/bot.png and Sources/IslandUI/Sprites.swift.",
        "// Do not hand-edit: re-run the script (issue #159).",
        "#pragma once",
        "",
        "#include <cstdint>",
        "",
        "namespace totem {",
        "namespace sprites {",
        "",
        f"inline constexpr uint8_t kFrameSize = {SIZE};",
        "",
        "/// Indexed palette, 0xRRGGBB. Index 0 is transparent (its value is unused).",
        f"inline constexpr uint8_t kPaletteSize = {len(palette)};",
        "inline constexpr uint32_t kPalette[kPaletteSize] = {",
        "    0x000000,  // transparent",
    ]
    lines += [f"    0x{rgb:06x}," for rgb in palette[1:]]
    lines += [
        "};",
        "",
        "/// One exported animation loop: its frames in kFrames start at",
        "/// `firstFrame`; `fpsMilli` is the pace in thousandths of a frame per second.",
        "struct Loop {",
        "    uint8_t firstFrame;",
        "    uint8_t frames;",
        "    uint16_t fpsMilli;",
        "};",
        "",
        "/// Frames and fps MUST mirror SpriteSheet.bot in Sources/IslandUI/Sprites.swift.",
        "/// Order: working, sleeping, finished, question (the sheet rows; error is not exported).",
        f"inline constexpr uint8_t kLoopCount = {len(table)};",
        "inline constexpr Loop kLoops[kLoopCount] = {",
    ]
    lines += [
        f"    {{{first}, {frames}, {fps_milli}}},  // {name}"
        for name, first, frames, fps_milli in table
    ]
    lines += [
        "};",
        "",
        "/// Palette indices, row-major, one 16x16 grid per frame.",
        f"inline constexpr uint8_t kFrameCount = {len(frames_out)};",
        "inline constexpr uint8_t kFrames[kFrameCount][kFrameSize * kFrameSize] = {",
    ]
    for name, index, indices in frames_out:
        lines.append(f"    {{  // {name} {index}")
        for y in range(SIZE):
            cells = ", ".join(str(i) for i in indices[y * SIZE : (y + 1) * SIZE])
            lines.append(f"        {cells},")
        lines.append("    },")
    lines += [
        "};",
        "",
        "}  // namespace sprites",
        "}  // namespace totem",
        "",
    ]
    return "\n".join(lines)


def main():
    header = build()
    if "--check" in sys.argv[1:]:
        try:
            with open(OUTPUT, encoding="utf-8") as current:
                same = current.read() == header
        except FileNotFoundError:
            same = False
        if not same:
            fail(f"{OUTPUT} is out of date: re-run scripts/export_totem_sprites.py")
        print(f"{OUTPUT} is up to date")
        return
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as out:
        out.write(header)
    print(f"wrote {OUTPUT}")


if __name__ == "__main__":
    main()
